

## Current mermaid rule graph
```{r rulegraph}
library(DiagrammeR)
library(DiagrammeRsvg)

mermaid("graph TB

subgraph  

0{ALL TARGETS}
1[ggplot_variable_freq]
2[get_sra_metadata]
3[leaflet_sample_gps]
4[qc_rawreads]
5[final_otu_files]
6[classify_otu97]
7[denoise_n_classify80]
8[align_n_filter]
9[make_contigs]
10[make_files]
11[get_references]
12[final_phylotype_files]
13[classify_phylotype]
14[final_asv_files]
15[classify_asv]
16[final_phylogeny_files]
17[classify_phylogeny]
18[subsample_otutable]
19[split_by_group]
20[count_groups]
21[get_dag]
22[interactive_report]
23[github_page_index]
22 --> 0
16 --> 0
3 --> 0
12 --> 0
4 --> 0
14 --> 0
18 --> 0
23 --> 0
1 --> 0
21 --> 0
5 --> 0
2 --> 1
2 --> 3
6 --> 5
7 --> 6
11 --> 7
8 --> 7
11 --> 8
9 --> 8
10 --> 9
13 --> 12
7 --> 13
15 --> 14
7 --> 15
17 --> 16
7 --> 17
20 --> 18
19 --> 18
5 --> 19
19 --> 20
21 --> 23

end

", width=1201.75)
```
<br><br>

## Complex mermaid DAG
```{r dag}
library(DiagrammeR)
library(DiagrammeRsvg)

mermaid("graph TB

subgraph  

0[ALL TARGETS]
1[ggplot_variable_freq]
2[get_sra_metadata]
3[leaflet_sample_gps]
4[qc_rawreads]
5[final_otu_files<br>finalotus<br>data/mothur/final/otu_analysis]
6[classify_otu97]
7[denoise_n_classify80]
8[align_n_filter]
9[make_contigs<br>outdir<br>data/qc/stats]
10[make_files<br>dataset<br>test<br>outdir<br>data/mothur/process]
11[get_references]
12[final_phylotype_files<br>finalphylotype<br>data/mothur/final/phylotype_analysis]
13[classify_phylotype]
14[final_asv_files<br>finalasv<br>data/mothur/final/asv_analysis]
15[classify_asv]
16[final_phylogeny_files<br>finalphylogeny<br>data/mothur/final/phylogeny_analysis]
17[classify_phylogeny<br>outdir<br>data/qc/stats]
18[denoise_n_classify80<br>outdir<br>data/mothur/process]
19[subsample_otutable]
20[split_by_group<br>group<br>sample]
21[split_by_group<br>group<br>control]
22[count_groups]
23[count_groups]
24[subsample_otutable]
25[get_dag]
26[interactive_report]
27[github_page_index]
1 --> 0
3 --> 0
4 --> 0
5 --> 0
12 --> 0
14 --> 0
16 --> 0
19 --> 0
24 --> 0
25 --> 0
26 --> 0
27 --> 0
2 --> 1
2 --> 3
6 --> 5
7 --> 6
8 --> 7
11 --> 7
9 --> 8
11 --> 8
10 --> 9
13 --> 12
7 --> 13
15 --> 14
7 --> 15
17 --> 16
18 --> 17
8 --> 18
11 --> 18
20 --> 19
21 --> 19
22 --> 19
23 --> 19
5 --> 20
5 --> 21
20 --> 22
21 --> 22
20 --> 23
21 --> 23
20 --> 24
21 --> 24
22 --> 24
23 --> 24
25 --> 27

end

", width=1201.75)
```