# config.yaml
# William L. Close

# Purpose: Snakemake config file containing user-provided settings for analyzing 16S data using mothur.

##################################################################
#
# Mothur
#
##################################################################

# NOTE: As required, change these settings before running workflow.

# Group names of mock samples (e.g. Mock1_S1_L001_R1_001.fastq.gz = Mock1).
mothurMock:
  - Mock1
  - Mock2
  - Mock3

# Group names of control samples (e.g. Water1_S2_L001_R1_001.fastq.gz = Water1).
mothurControl:
  - Water1
  - Water2
  - Water3

# Desired alpha diversity metrics.
mothurAlpha:
  - nseqs
  - coverage
  - invsimpson
  - shannon
  - sobs

# Desired beta diversity metrics.
mothurBeta:
  - sharedsobs
  - thetayc
  - braycurtis

# Minimum read threshold for subsampling.
subthresh: 1000



# NOTE: Leave these settings as is.

# Read numbers
readNum:
  - R1
  - R2

mothurGroups:
  - sample
  - mock
  - control

# Random seed
seed: 20170415
