# config.yaml
# William L. Close

# Purpose: Snakemake config file containing user-provided settings for analyzing 16S data using mothur.

##################################################################
#
# Mothur
#
##################################################################

# NOTE: As required, change these settings before running workflow.

# Group names of mock samples (e.g. Mock1_S1_L001_R1_001.fastq.gz = Mock1).
mothurMock:
  - Mock1
  - Mock2

# Group names of control samples (e.g. Water1_S2_L001_R1_001.fastq.gz = Water1).
mothurControl:
  - NA
  - Water
  - Water2

# Desired alpha diversity metrics.
mothurAlpha:
  - nseqs
  - coverage
  - invsimpson
  - shannon
  - sobs

# Desired beta diversity metrics.
mothurBeta:
  - sharedsobs
  - thetayc
  - braycurtis

# Minimum read threshold for subsampling.
subthresh: 1000



# NOTE: Leave these settings as is.

# Read numbers
readNum:
  - R1
  - R2

mothurGroups:
  - sample
  - mock
  - control

# Random seed
seed: 20170415

dataset: test
workdir: .
sampledir: "data/raw"
outputdir: "data/process/"
alignment: data/references/silva.seed.align
classifier: data/references/trainset9_032012.pds.fasta
taxonomy: data/references/trainset9_032012.pds.tax
maxambig: 0
maxlength: 275
start: 11894
end: 25319
keepdots: F
maxhomop: 8
vertical: T
trump: .
diff: 2
dereplicate: t
cutoff: 80
taxon: Chloroplast-Mitochondria-unknown-Archaea-Eukaryota
group: Mock
dist_cutoff: 0.20